### ISSUE TITLE
ImportError: cannot import name dataclass_transform

### ISSUE THREAD

**Issue by cheukhin1024** [microsoft/planetary-computer-sdk-for-python#48] opened 2022-10-05 05:51 UTC
Cannot import name `dataclass_transform` by PyPl installing` planetary-computer`

![擷取](https://user-images.githubusercontent.com/70860455/193990380-a0593c38-85a8-4d8a-82ef-c6c4a44e0cac.JPG)

**Comment by TomAugspurger** [comment] 2022-10-05 11:35
What version of Python do you have, and how did you install planetary-computer? I can't reproduce this in a new virtual environment

```python
❯ python3 -m pip install planetary-computer
❯ python3 -c "import planetary_computer"
```

Are you able to post the full traceback? `dataclass_transform` isn't a (direct) dependency of planetary computer, but maybe one of the dependencies is pulling it in.

**Comment by cheukhin1024** [comment] 2022-10-12 04:16
> What version of Python do you have, and how did you install planetary-computer? I can't reproduce this in a new virtual environment
> 
> ```python
> ❯ python3 -m pip install planetary-computer
> ❯ python3 -c "import planetary_computer"
> ```
> 
> Are you able to post the full traceback? `dataclass_transform` isn't a (direct) dependency of planetary computer, but maybe one of the dependencies is pulling it in.

My Azure Databricks is using 11.2 ML Databricks Runtime Version ([https://docs.databricks.com/release-notes/runtime/11.2ml.html]). I assume the Python version is 3.7/3.8. 

I installed the PyPl `planetary_computer` package

**Comment by TomAugspurger** [comment] 2022-10-12 11:20
Can you create a clean virtual environment and try there? I'm wondering if some existing package is incompatible with our dependencies (possibly pydantic is pulling in this dependency, but that should have been fixed in https://github.com/pydantic/pydantic/issues/4423).

**Comment by cheukhin1024** [comment] 2022-10-12 16:22
The code works in Planetary Computer Hub, but it doesn't work in Azure Databricks. 

Here are the [Databricks Runtime 11.2 Version Libaries](
https://learn.microsoft.com/en-us/azure/databricks/release-notes/runtime/11.2):

**Comment by TomAugspurger** [comment] 2022-10-12 16:26
I haven't used Databricks before, so it'll be a while before I can look into this. But I suspect it's nothing particular to this package and would happen any time you try to import pydantic / its dependencies.

I'm guessing it's "just" a matter of getting the package configuration correct.

**Comment by cheukhin1024** [comment] 2022-10-12 17:15
There is **Pydantic 1.9.2** in [Databricks Runtime 11.2 ML Version](https://learn.microsoft.com/en-us/azure/databricks/release-notes/runtime/11.2ml) while there is no Pydantic in [Databricks Runtime 11.2 Version](https://learn.microsoft.com/en-us/azure/databricks/release-notes/runtime/11.2), but it also has the same error.

**Comment by TomAugspurger** [comment] 2023-03-19 15:37
FYI, I've heard that things *do* work with the Runtime 11.3 version, as long as you restart things after installing `planetary-computer`.

**Closed by TomAugspurger** 2023-03-19 15:37 UTC
